# Generated by Django 4.1.3 on 2022-11-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_person_name_person_age_person_gender_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="person", new_name="input",),
    ]
