# Generated by Django 4.1.3 on 2022-11-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_person_input"),
    ]

    operations = [
        migrations.AlterField(
            model_name="input",
            name="age",
            field=models.CharField(default="prefer not to answer", max_length=50),
        ),
    ]
