# Generated by Django 4.1.3 on 2022-12-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_input_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="input",
            name="age",
            field=models.CharField(default="fill in your info", max_length=50),
        ),
        migrations.AlterField(
            model_name="input",
            name="gender",
            field=models.CharField(default="fill in your info", max_length=50),
        ),
        migrations.AlterField(
            model_name="input",
            name="race",
            field=models.CharField(default="fill in your info", max_length=50),
        ),
    ]
